### ISSUE TITLE
snv calling

### ISSUE THREAD

**Issue by YuelinYao** [IanevskiAleksandr/sc-type#12]
Thank you for this excellent tool! How could we find the cancer cell identification example code (SNV calling)?

**Comment by AndreaYCT** [comment]
I've tried the scType in R and app. This tool is amazingly great!! Hope the database will increasing in the future.
I'd like to learn the SNV calling function too!!!

**Comment by IanevskiAleksandr** [comment]
Dear @YuelinYao  @AndreaYCT ,

We indeed had our own function to determine malignant/healthy cells. Even though, this feature (SNV calling) was initially available, it was later disabled due to variations in BAM input file formats which made it difficult to create a versatile function. However, a new function is currently being developed that will be more flexible and ask only for scRNA-seq expression matrix as input. We anticipate that this new function for annotating malignant/healthy cells will be available in ~2 months.

I will keep you updated.

BR,
Aleksandr
