### ISSUE TITLE
SNV analysis from the paper

### ISSUE THREAD

**Issue by pedriniedoardo** [IanevskiAleksandr/sc-type#26]
Hello, 
In your [paper](https://www.nature.com/articles/s41467-022-28803-w), you say, "ScType implements a single-cell single-nucleotide variant (SNV) calling option to distinguish between malignant and non-malignant cells". I cannot find any function or recommended workflows to reproduce the analysis shown in the paper. Can you help with that?

**Comment by IanevskiAleksandr** [comment]
Dear @pedriniedoardo,

We indeed had our own function to determine malignant/healthy cells. Even though, this feature (SNV calling) was initially available, it was later disabled due to variations in BAM input file formats which made it difficult to create a versatile function. However, a new function is currently being developed that will be more flexible and ask only for scRNA-seq expression matrix as input. We anticipate that this new function for annotating malignant/healthy cells will be available in ~2 months.

BR,
Aleksandr
