### ISSUE TITLE
Error in Z[cell_markers_genes_score[jj, "gene_"], ] :    subscript out of bounds

### ISSUE THREAD

**Issue by Flu09** [IanevskiAleksandr/sc-type#65]
es.max <- sctype_score(scRNAseqData = scRNAseqData_scaled, scaled = TRUE, gs = gs_list$gs_positive, gs2 = gs_list$gs_negative)
Error in Z[cell_markers_genes_score[jj, "gene_"], ] : 
  subscript out of bounds

**Comment by Flu09** [comment]
sample1 <- CreateSeuratObject(sample1)
sample2 <- CreateSeuratObject(sample2)
merged <- merge(sample1, sample2)
merged <- JoinLayers(merged)
merged <- NormalizeData(merged)
merged <- FindVariableFeatures(merged)
merged <- ScaleData(merged)

**Comment by cwarden45** [comment]
**I also encountered a similar issue when I tried to run the tutorial data (as well as some public data, downloaded as a .h5 file).**

If you closed the issue because you found a solution, then it may be helpful to share your solution with others.  Or, I am not sure if the issues was resolved with a revised version of the code.

I did _not_ run the exact command that you ran, but I hope that the following might help:

**1)** In order to run `auto_detect_tissue_type`, I downloaded and modified the file to be `auto_detect_tissue_type-MOD.R`.

Here is the part that I changed:

```
## REPLACEMENT CODE
obj=as.matrix(GetAssayData(Seurat_object))

## ORIGINAL CODE
#package_type <- substr(packageVersion("Seurat"), 1, 1)
#data_type <- if (scaled) "scale.data" else "counts"
#obj <- if (package_type == "5") {
#as.matrix(seuratObject[[assay]]$data_type)
#} else {
#as.matrix(seuratObject[[assay]]@data_type)
#}
```

I noticed that `readRDS(gzcon(url('https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/exampleData.RDS')))` was *not* a Seurat object.  So, that was the basis for making the change, along with an explanation from [this issue](https://github.com/satijalab/seurat/issues/686).

However, I didn't need to create modified versions of the other functions.

**2)** To be clear, I did not test running the code below myself.

However, I think there is a modified version of `sctype_score.R` within **software/sctype** in https://zenodo.org/records/8317410 (with code to run _SingleR_ and _ScType_).

At least at a particular point in time, I am not sure if that might relate in some way to what you encountered?
